Repository MultiPoolMiner/MultiPoolMiner, pull requests merged in 2018-07, with the labels that each got.

#1935 Benchmark ExtendInterval miners first
  MultiPoolMiner.ps1
Labels: enhancement

#1933 Fix MinerNeedingBenchmarks counter
  MultiPoolMiner.ps1
Labels: bug, fixed

#1961 Update Algorithms.txt
  Algorithms.txt
Labels: enhancement, priority

#1954 Change config file handling
  MultiPoolMiner.ps1
Labels: available for testing, enhancement

#1950 CcminerZealot Update to 1.12
  MinersLegacy/CcminerZealot.ps1
Labels: available for testing, enhancement

#1948 Update documentation
  README.md
  README.txt
Labels: enhancement

#1941 ShowPoolBalancesExcludedPools $false
  MultiPoolMiner.ps1
Labels: bug, fixed

#1938 Force API calls to return arrays, add /currentprofit
  API.psm1
Labels: fixed

#1960 Ethminer: Update to version 0.14.0
  MinersLegacy/EthminerAmd.ps1
  MinersLegacy/EthminerAmd.txt
  MinersLegacy/EthminerNvidia.ps1
  MinersLegacy/EthminerNvidia.txt
Labels: enhancement

#1963 Useless guru update readme
  README.md
  README.txt
Labels: fixed

#1966 Fix MinMemGB
  MinersLegacy/ClaymoreEthash.ps1
Labels: bug, fixed

#1868 Detect CPUs through CIM instead of OpenCL
  Include.psm1
Labels: available for testing, enhancement, fixed

#1939 Web interface
  web/activeminers.html
  web/allpools.html
  web/bestpools.html
  web/css/dashboard.css
  web/devices.html
  web/index.html
  web/js/utilities.js
  web/miners.html
  web/minerstats.html
  web/parts/foot.html
  web/parts/head.html
  web/runningconfig.html
  web/savedconfig.html
  web/scripts/resetallbenchmarks.ps1
  web/scripts/resetzerohashrateminers.ps1
Labels: available for testing, enhancement

#1991 Ethminer: Fix MinMem
  MinersLegacy/EthminerAmd.ps1
  MinersLegacy/EthminerNvidia.ps1
Labels: bug, fixed

#1993 Excavator API
  APIs/Excavator.ps1
Labels: enhancement

#1952 Fix parameter -MinerName & -ExcludeMinerName
  MultiPoolMiner.ps1
Labels: bug, enhancement, fixed

#2003 Delete CcminerDelos.ps1
  MinersLegacy/CcminerDelos.ps1
Labels: priority

#2004 ClaymoreDual: Update to version 11.9
  MinersLegacy/ClaymoreEthash.ps1
Labels: fixed, priority

#2018 Algorithms.txt: Add Equihash algorithm variants
  Algorithms.txt
Labels: enhancement, help wanted, priority

#1971 Update phoenix miner to version 3.0c
  MinersLegacy/PhoenixMinerAmd.ps1
  MinersLegacy/PhoenixMinerAmd.txt
  MinersLegacy/PhoenixMinerNvidia.ps1
  MinersLegacy/PhoenixMinerNvidia.txt
Labels: available for testing, enhancement

#1846 CPUMiner-TPruvot: Remove unsupported HMQ1725
  MinersLegacy/CPU-CpuminerTpruvotAvx2.ps1
  MinersLegacy/CPU-CpuminerTpruvotCore2.ps1
  MinersLegacy/CPU-CpuminerTpruvotCorei7.ps1
  MinersLegacy/CpuminerTpruvotAvx2.ps1
  MinersLegacy/CpuminerTpruvotCore2.ps1
  MinersLegacy/CpuminerTpruvotCorei7.ps1
Labels: enhancement, help wanted

#2042 Add Equihash variants Zel & BtcZ for ZergPool
  Pools/ZergPool.ps1
Labels: available for testing, enhancement
