Repository MultiPoolMiner/MultiPoolMiner, pull requests merged in 2018-06, with the labels that each got.

#1812 Fix Get-Stat
  Include.psm1
Labels: fixed

#1787 Add CcminerDelos
  Miners/CcminerDelos.ps1
Labels: available for testing, enhancement, help wanted

#1783 Excavator 1.4.4a: Enable DualMining
  APIs/Excavator.ps1
  MinersLegacy/Excavator.ps1
Labels: available for testing, enhancement

#1849 Will no longer attempt to run miners for hardware that is not present
  MultiPoolMiner.ps1
Labels: bug, fixed, priority

#1861 CcminerDelos: Update to Version 1.3.0a
  MinersLegacy/CcminerDelos.ps1
Labels: enhancement

#1860 Nicehash: Ignore dead algorithms
  Pools/NiceHash.ps1
Labels: enhancement

#1859 Use divisor from pool
  Pools/Hashrefinery.ps1
Labels: enhancement

#1862 CcminerDelos: Fix Hashrates
  MinersLegacy/CcminerDelos.ps1
Labels: bug, fixed, priority

#1863 CcminerZealot: Update to version 1.11
  MinersLegacy/CcminerZealot.ps1
Labels: enhancement

#1870 Fix ZergPool divisor problem
  Pools/ZergPool.ps1
Labels: fixed

#1885 Fix parameter -MinerName & -ExludeMinerName
  MinersLegacy/ClaymoreEthash.ps1
  MinersLegacy/Excavator.ps1
  MultiPoolMiner.ps1
Labels: available for testing, enhancement

#1891 ExtendInterval as miner property
  Include.psm1
  MultiPoolMiner.ps1
Labels: available for testing, enhancement

#1898 CcminerKlausT r11 fix
  MinersLegacy/CcminerKlaust.ps1
Labels: enhancement

#1897 CcminerTpruvot v2.2.6
  MinersLegacy/CcminerTpruvot.ps1
Labels: enhancement

#1907 Add CcminerPigeonCoin
  MinersLegacy/CcminerPigeonCoin.ps1
Labels: enhancement

#1893 Fix Benchmarks
  MultiPoolMiner.ps1
Labels: enhancement

#1896 ExtendInterval for selected algorithms
  MinersLegacy/CcminerAnxmodPhi.ps1
  MinersLegacy/CcminerDelos.ps1
  MinersLegacy/CcminerNevermore.ps1
  MinersLegacy/CcminerSuprMiner.ps1
  MinersLegacy/CcminerZealot.ps1
Labels: enhancement

#1913 Update Config.default.txt
  Config.default.txt
Labels: bug, fixed

#1925 Support for config files
  Config.default.txt
  MultiPoolMiner.ps1
Labels: available for testing, enhancement

#1918 Fix ExtendInterval
  MultiPoolMiner.ps1
Labels: bug, fixed

#1923 No driver warning on non-Nvidia systems
  MinersLegacy/CcminerKlaust.ps1
  MinersLegacy/CcminerPigeonCoin.ps1
Labels: bug, fixed
