Repository MultiPoolMiner/MultiPoolMiner, pull requests merged in 2018-03, with the labels that each got.

#1447 BlazePool.ps1: Fix worker name display @ pool
  Pools/BlazePool.ps1
Labels: bug, fixed

#1439 Add logfile path to miner object
  Include.psm1
Labels: enhancement

#1461 ZergPool.ps1: Fix divisors & password parameter
  Pools/ZergPool.ps1
Labels: bug, fixed

#1466 CcminerKlausT: Update to version 8.21
  Miners/CcminerKlaust.ps1
Labels: bug, enhancement, fixed

#1234 Miner config enhancements
  Include.psm1
  MultiPoolMiner.ps1
Labels: enhancement

#1443 Add basic API for monitoring the script
  API.psm1
  APIDocs.html
  MultiPoolMiner.ps1
Labels: enhancement

#1513 CcminerSuprMiner: Supports X16R & X16S
  Algorithms.txt
  Miners/CcminerSuprMiner.ps1
Labels: enhancement

#1514 ClaymoreNvidia: Unified miner
  Miners/ClaymoreNvidia.ps1
  Miners/ClaymoreNvidia.txt
  Miners/ClaymoreNvidia2gbBlake2s20.txt
  Miners/ClaymoreNvidia2gbBlake2s30.txt
  Miners/ClaymoreNvidia2gbBlake2s40.txt
  Miners/ClaymoreNvidia2gbDecred20.txt
  Miners/ClaymoreNvidia2gbDecred30.txt
  Miners/ClaymoreNvidia2gbDecred40.txt
  Miners/ClaymoreNvidia2gbKeccak20.txt
  Miners/ClaymoreNvidia2gbKeccak30.txt
  Miners/ClaymoreNvidia2gbKeccak40.txt
  Miners/ClaymoreNvidia2gbLbry20.txt
  Miners/ClaymoreNvidia2gbLbry30.txt
  Miners/ClaymoreNvidia2gbLbry40.txt
  Miners/ClaymoreNvidia2gbPascal20.txt
  Miners/ClaymoreNvidia2gbPascal30.txt
  Miners/ClaymoreNvidia2gbPascal40.txt
  Miners/ClaymoreNvidiaBlake2s20.txt
  Miners/ClaymoreNvidiaBlake2s30.txt
  Miners/ClaymoreNvidiaBlake2s40.txt
  Miners/ClaymoreNvidiaDecred20.txt
  Miners/ClaymoreNvidiaDecred30.txt
  Miners/ClaymoreNvidiaDecred40.txt
  Miners/ClaymoreNvidiaKeccak20.txt
  Miners/ClaymoreNvidiaKeccak30.txt
  Miners/ClaymoreNvidiaKeccak40.txt
  Miners/ClaymoreNvidiaLbry20.txt
  Miners/ClaymoreNvidiaLbry30.txt
  Miners/ClaymoreNvidiaLbry40.txt
  Miners/ClaymoreNvidiaPascal20.txt
  Miners/ClaymoreNvidiaPascal30.txt
  Miners/ClaymoreNvidiaPascal40.txt
Labels: enhancement, priority
